package com.abcd.demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SomeName implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "val")
	private java.lang.String val;

	public SomeName() {
	}

	public java.lang.String getVal() {
		return this.val;
	}

	public void setVal(java.lang.String val) {
		this.val = val;
	}

	public SomeName(java.lang.String val) {
		this.val = val;
	}

}